M48
; DRILL file {KiCad 7.0.9} date Sat Dec  2 16:20:17 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-02T16:20:17-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X194.272Y-80.747
X194.272Y-85.747
T2
X105.926Y-95.653
X105.926Y-107.653
T3
X104.0Y-68.0
X104.0Y-131.0
X194.0Y-68.0
X194.0Y-131.0
T0
M30
