M48
; DRILL file {KiCad 8.0.3} date 2024-11-24T16:31:50-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-24T16:31:50-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X187.695Y-139.43
X193.475Y-139.43
T2
X108.835Y-49.68
X108.835Y-141.68
X200.835Y-49.68
X200.835Y-141.68
M30
